import streamlit as st

st.title("Safietou Abdou Aziz Diop")

st.header("Technicienne supérieure en Sciences et Techniques Agricoles, Alimentaires et Nutritionnelles")
st.write("___________________________________________________________________________________________________")
st.markdown("Dynamique et motivée, avec de solides compétences en agroécologie, phytosanitaire et pratiques agricoles , je suis capable de travailler aussi bien en équipe qu’en autonomie, avec une bonne capacité d’adaptation et un réel sens de l’organisation. À l’aise avec les techniques de multiplication végétative, le suivi des cultures et les calendriers culturaux, tout en faisant preuve de rigueur, de sérieux et d’un bon sens des responsabilités. Sérieuse et toujours prête à développer de nouvelles compétences professionnelles.")

st.sidebar.markdown("## Informations personnelles")
st.sidebar.image("WhatsApp Image 2026-05-10 at 18.49.06.jpeg",width=190)
st.sidebar.markdown("📧 Email: sofiadiop01@gmail.com")
st.sidebar.markdown("📍Adresse: Dakar, Sénégal")

st.sidebar.markdown("## 🌍 Langues")
st.sidebar.markdown("Français (C1)")
st.sidebar.markdown(" Anglais (B1)")
st.sidebar.markdown("## Engagements associatifs")
st.sidebar.markdown("* Vice présidente d'un club environnemental universitaire (EcoHuman)")
st.sidebar.markdown("* Membre de l'Alliance des Agronomes de l'Université Amadou Mahtar Mbow")
st.sidebar.markdown("* Membre d'une organisation à vocation sociale ( Unité des Coeurs)")
st.sidebar.markdown("## Informations complementaires")
st.sidebar.markdown("Permis de conduire categorie B")


st. subheader ("FORMATIONS")
st.write ("* Licence en Sciences et Techniques Agricoles, Alimentaire et Nutritionnelles")
st.write("2024-2027 (En cours)")
st.write ("* BACCALAUREAT SCIENTIFIQUE")
st.write("2023-2024")
st. subheader ("EXPERIENCES PROFESSIONNELLES")
st.write("Stage au Centre de Formation Professionnelle Horticole de Dakar (CFPH) Durée : 1er Novembre 2025 - 30 Novembre 2025  ")
st.markdown("* Participation aux activités pratiques de formation agricole")
st.markdown(" * Apprentissage des techniques de base de production végétale et d’entretien des plantes")
st.markdown("* Assistance aux travaux de terrain et à l’entretien de l’exploitation")
st.markdown("* Observation et application de pratiques agricoles durables")
st.markdown("* Développement de l’esprit d’équipe et des compétences pratiques en agriculture")
st. subheader ("COMPETENCES")
st.subheader("Competences techniques agronomiques ")
st.markdown(" * Réaliser des analyses microbiologiques")
st.markdown("* Manipuler les équipements de laboratoire")
st.markdown("* Collaborer en équipe de production")
st.markdown(" * Organiser les activités agricoles selon les périodes culturales")
st.markdown("* Observer et diagnostiquer l’état phytosanitaire des cultures")
st.markdown("* Identifier les maladies et ravageurs des plantes")
st.subheader("Competences logistiques")
st.markdown("* Suites bureautiques")
    